select 
    {{ dbt_utils.generate_surrogate_key(['id','name'])}} as listing_key,
    id as listing_id ,
    name ,
    neighborhood_overview,
    picture_url ,
    host_id,
    host_url,
    host_name ,
    host_since ,
    host_location,
    host_about ,
    host_response_time  ,
   TO_NUMBER(NULLIF(REPLACE(host_response_rate, '%', ''), 'N/A'))/100 AS host_response_rate,
TO_NUMBER(NULLIF(REPLACE(host_acceptance_rate, '%', ''), 'N/A'))/100 AS host_acceptance_rate,
 host_is_superhost ,
    host_picture_url  ,
    host_neighbourhood  ,
    host_listings_count,
    host_total_listings_count,
    host_verifications ,
    host_identity_verified ,
    neighbourhood_cleansed  ,
    latitude ,
    longitude ,
    property_type ,
    room_type ,
    accommodates ,
    TO_NUMBER(NULLIF(REPLACE(REPLACE(price, '$', ''), ',', ''), 'N/A')) AS price,
    number_of_reviews,
    number_of_reviews_ltm ,
    number_of_reviews_l30d ,
    first_review ,
    last_review ,
    review_scores_rating ,
    review_scores_accuracy ,
    review_scores_cleanliness ,
    review_scores_checkin ,
    review_scores_communication,
    review_scores_location ,
    review_scores_value ,
    license,
    instant_bookable ,
    reviews_per_month 

from {{source('airbnb_pipeline','listings')}}
